sudo: false
dist: trusty

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.4
      env: WP_VERSION=latest
    - php: 7.4
      env: WP_VERSION=trunk
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1

before_script:
  - |
    # Install the specified version of PHPUnit depending on the PHP version:
    if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
      case "$TRAVIS_PHP_VERSION" in
        7.2|7.1|7.0|nightly)
          echo "Using PHPUnit 6.x"
          composer global require "phpunit/phpunit:^6"
          ;;
        5.6|5.5|5.4)
          echo "Using PHPUnit 4.x"
          composer global require "phpunit/phpunit:^4"
          ;;
        *)
          echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
          exit 1
          ;;
      esac
    fi
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then
      composer global require "phpunit/phpunit=5.7.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
    fi
